version: '3.9'

services:
  monitorias-app:
    container_name: monitorias-app
    image: yanmelo/monitorias-app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://monitorias-db:5432/monitorias
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on: 
      - monitorias-db

  monitorias-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
