package com.yandemelo.monitorias.entities.enums;

public enum CursosExistentes {
    ENGENHARIA_DA_COMPUTACAO,
    ENGENHARIA_CIVIL,
    ENGENHARIA_DE_CONTROLE_E_AUTOMACAO,
    ENGENHARIA_ELETRICA_ELETRONICA,
    ENGENHARIA_ELETRICA_ELETROTECNICA,
    ENGENHARIA_ELETRICA_TELECOMUNICACAO,
    ENGENHARIA_MECANINCA,
    FISICA_DE_MATERIAIS
    
}
